import Head from 'next/head'
// import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import SearchBar from '../src/containers/SearchBar/SearchBar';
import Footer from '../src/components/Footer/Footer';
import NewsCard from '../src/components/NewsCard/NewsCard';
import CategoryBar from '../src/containers/CategoryBar/CategoryBar';

const { appHeader } = styles;

const api = {
  apiKey: process.env.REACT_MEDIA_KEY,
  baseUrl: `http://api.mediastack.com/v1/news`
};

export const getStaticProps = async () => {

  const res = await fetch(`${api.baseUrl}?access_key=${api.apiKey}&countries=us`);
  const data = await res.json();

  return {
    props: {
      articles: data
    },
  };
};

export default function Home({ articles }) {

  console.log(articles)

  return (
    <div className={styles.container}>
      <Head>
        <title>News Next Application</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <h1 className={appHeader}>
          Welcome to the News!
        </h1>
      </header>
      <main>
        <p className={['centerText'].join('')}>
          Welcome to the <span>News Next Application</span>! To begin, select a category below
          or enter into search field and relevant articles will come up.
        </p>
        <SearchBar />
        <CategoryBar />
        {articles.data?.map((news, id) => {
          return (
            <NewsCard
              key={id}
              article={news.title}
              articleURL={news.url}
              image={news.image}
              description={news.description}
              tags={news.category} />
          )
        })
        }
      </main>
      <Footer />
    </div>
  );
};