import Head from 'next/head'
// import Image from 'next/image'
import styles from '../styles/Home.module.css'
import SearchBar from '../src/containers/SearchBar/SearchBar';
import Footer from '../src/components/Footer/Footer';

const { appHeader } = styles;

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>News Next Application</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <h1 className={appHeader}>
          Welcome to the News!
        </h1>
        <span className={['centerText'].join('')}>Powered by NextJS</span>
      </header>
      <main>
        <p className={['centerText'].join('')}>
          Welcome to the <span>News Next Application</span>! To begin, select a category below
          or enter into search field and relevant articles will come up.
        </p>
        <SearchBar />
      </main>
      <Footer />
    </div>
  );
};